# Uncomment to save power by deep-sleeping when idle (PillBug/BLE builds only)
CONFIG_ZMK_SLEEP=y

# Uncomment to change how long before the keyboard goes idle (milliseconds)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_STUDIO=y
